name: 谷歌扩展发布

on:
  push:
    branches: [ "master" ]  # 触发分支

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # 需要写权限才能创建 Release
      issues: read     # 其他相关权限（视情况而定）

    steps:
      # Step 1: 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # Step 2: 配置 NodeJS 环境
      - name: 设置 NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Step 3: 恢复依赖项
      - name: 安装依赖项
        run: npm install

      # Step 4: 构建项目
      - name: 构建项目
        run: npm run zip

      - name: 打印当前文件夹
        run: dir

      - name: 打印.output文件夹
        run: dir .\.output

      # Step 5: 上传文件到infinityfree
      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./.output/  # 直接使用本地生成的目录
          server-dir: ${{ secrets.REMOTE_DIR }}
          dry-run: false  # 实际执行上传
          dangerous-clean-slate: true  # 首次部署建议启用-20250607首次部署
